name: deploy website
on:
  # 一応動確のために手動で GitHub Actions を実行可能にする
  # その際の引数として checkout 時の ref を渡している
  # default 部分はリポジトリに設定されているデフォルトブランチを指定する
  workflow_dispatch:
    inputs:
      ref:
        description: branch|tag|SHA to checkout
        default: "main"
        required: true
  # 毎日日本時間の 11時 に GitHub Actions が実行される (cron の時刻は UST)
  # 実行の際に参照されるブランチは上記の default で指定したものが使用される
  schedule:
    - cron: "39 21 * * *"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      # 投稿内容を更新するために npm run build:posts を走らせる
      - name: Create env file
        run: |
          touch .env.local
          echo "NEXT_PUBLIC_ENDPOINT=${{ secrets.NEXT_PUBLIC_ENDPOINT }}" >> .env.local
          echo "NEXT_PUBLIC_SHOBOI_ENDOPOINT=${{ secrets.NEXT_PUBLIC_SHOBOI_ENDOPOINT }}" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_MESSAGIN_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGIN_SENDER_ID }}" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}" >> .env.local
          echo "NEXT_PUBLIC_TOKEN_KEY=${{ secrets.NEXT_PUBLIC_TOKEN_KEY }}" >> .env.local
          echo "NEXT_PUBLIC_ADMIN_SECRET=${{ secrets.NEXT_PUBLIC_ADMIN_SECRET }}" >> .env.local
          echo "NEXT_PUBLIC_API_ENDPOINT=${{ secrets.NEXT_PUBLIC_API_ENDPOINT }}" >> .env.local
      - name: Recreate all posts
        shell: bash
        run: yarn && yarn build &&  npm install -g firebase-tools && firebase experiments:enable webframeworks
      - name: firebase Action
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NERD_381210 }}"
          channelId: live
          projectId: nerd-381210
